name: baptist_hymnal
publish_to: "none"
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cuberto_bottom_bar: ^1.1.1+1
  cupertino_icons: ^1.0.3
  draggable_scrollbar_sliver: ^0.0.3
  flutter_staggered_animations: ^1.0.0
  anim_search_bar: ^2.0.2
  google_nav_bar: ^5.0.5
  line_icons: ^2.0.1
  path_provider: ^2.0.11
  provider: ^5.0.0
  settings_ui: ^2.0.2
  share: ^0.6.4+2
  shared_preferences: ^2.0.6
  equatable: ^2.0.3
  splashscreen: ^1.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/hymnal1.jpg
    - assets/images/hymnal2.jpg
    - assets/images/hymnal3.jpg

  fonts:
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf
